
# screen
WIDTH, HEIGHT = 1300, 800
HALF_WIDTH, HALF_HEIGHT = WIDTH // 2, HEIGHT // 2
CENTER = (HALF_WIDTH, HALF_HEIGHT)
SCREEN = (WIDTH, HEIGHT)

# player
PLAYER_SIZE = (30, 50)
PLAYER_POS = CENTER
PLAYER_SPEED = 4
JUMP_POWER = 15
MAX_VERTICAL_SPEED = 15
JUMP_DELEY = 1230

# camera
# left, top, right, bottom
CAMERA_RECT = (int(WIDTH * .2), int(HEIGHT * .1), int(WIDTH * .2), int(HEIGHT * .1))

# map
TILE_SIZE = 60

# world
GRAVITY = .4

# bullet
AUTO_REMOVE_DELEY = 10000  # 10 sec